version: '3.3'
services:
  sklep-db:
    image: mysql:8.0.23
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: 'sklep-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sklep-db-user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'abc123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'abc123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: {}
